export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const GET_TOP_ARTISTS = 'GET_TOP_ARTISTS';
export const GET_TOP_TRACKS = 'GET_TOP_TRACKS';
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';